#!/usr/bin/env bash
# install-hooks.sh — make the local CI mirror an enforced git gate.
#
# Writes a ``pre-push`` hook that runs ``make preflight``, so a push that
# would turn the server CI red is blocked on your machine instead. Safe
# to re-run (idempotent).
#
# Why the hooksPath dance below: git honours exactly ONE hooks directory.
# This machine may set a *global* ``core.hooksPath`` (e.g. an
# anti-attribution ``prepare-commit-msg``), which would otherwise shadow a
# hook dropped in ``.git/hooks``. So we point ``core.hooksPath`` at
# ``.git/hooks`` for THIS repo only (global config is never touched) and
# copy any pre-existing global hooks in, so they keep firing here too.
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"
hooks_dir="$repo_root/.git/hooks"
mkdir -p "$hooks_dir"

# Preserve hooks from a global hooksPath (e.g. the no-attribution guard)
# by copying them into this repo's hook dir before we take it over.
global_hooks="$(git config --global --get core.hooksPath || true)"
if [[ -n "${global_hooks}" ]]; then
	gdir="${global_hooks/#\~/$HOME}"
	if [[ -d "$gdir" ]]; then
		for h in "$gdir"/*; do
			[[ -f "$h" ]] || continue
			cp -f "$h" "$hooks_dir/$(basename "$h")"
			chmod +x "$hooks_dir/$(basename "$h")"
		done
	fi
fi

# Route this repo's hooks to .git/hooks (repo-local; global stays as-is).
git config --local core.hooksPath .git/hooks

# Write the pre-push gate. --no-verify still lets you bypass in a pinch.
cat >"$hooks_dir/pre-push" <<'HOOK'
#!/usr/bin/env bash
# pre-push — local CI mirror. Blocks a push that would fail the server.
# Auto-generated by scripts/install-hooks.sh. Bypass with `--no-verify`.
set -euo pipefail
echo "▶ running local preflight (mirror of CI) before push…"
make -s preflight
HOOK
chmod +x "$hooks_dir/pre-push"

echo "✅ pre-push hook installed → runs 'make preflight' before every push"
